if(EXISTS "D:/pyproject/kctsb/build-release/tests/test_integration[1]_tests.cmake")
  include("D:/pyproject/kctsb/build-release/tests/test_integration[1]_tests.cmake")
else()
  add_test(test_integration_NOT_BUILT test_integration_NOT_BUILT)
endif()
