if(EXISTS "D:/pyproject/kctsb/build-release/tests/test_random[1]_tests.cmake")
  include("D:/pyproject/kctsb/build-release/tests/test_random[1]_tests.cmake")
else()
  add_test(test_random_NOT_BUILT test_random_NOT_BUILT)
endif()
