if(EXISTS "D:/pyproject/kctsb/build-release/tests/test_aes[1]_tests.cmake")
  include("D:/pyproject/kctsb/build-release/tests/test_aes[1]_tests.cmake")
else()
  add_test(test_aes_NOT_BUILT test_aes_NOT_BUILT)
endif()
