if(EXISTS "D:/pyproject/kctsb/build-release/tests/test_benchmark[1]_tests.cmake")
  include("D:/pyproject/kctsb/build-release/tests/test_benchmark[1]_tests.cmake")
else()
  add_test(test_benchmark_NOT_BUILT test_benchmark_NOT_BUILT)
endif()
