if(EXISTS "D:/pyproject/kctsb/build-release/tests/test_hash[1]_tests.cmake")
  include("D:/pyproject/kctsb/build-release/tests/test_hash[1]_tests.cmake")
else()
  add_test(test_hash_NOT_BUILT test_hash_NOT_BUILT)
endif()
